// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TVMaze.Infrastructure.EntityFramework;

namespace TVMaze.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190308134202_InitialCreateDatabase")]
    partial class InitialCreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TVMaze.Infrastructure.Data.Entities.Cast", b =>
                {
                    b.Property<long>("CastId");

                    b.Property<string>("Birthday");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("CastId");

                    b.ToTable("Cast");
                });

            modelBuilder.Entity("TVMaze.Infrastructure.Data.Entities.CastShow", b =>
                {
                    b.Property<long>("CastShowId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CastId");

                    b.Property<long>("ShowId");

                    b.HasKey("CastShowId");

                    b.HasIndex("CastId");

                    b.HasIndex("ShowId");

                    b.ToTable("CastShow");
                });

            modelBuilder.Entity("TVMaze.Infrastructure.Data.Entities.Show", b =>
                {
                    b.Property<long>("ShowId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ShowId");

                    b.ToTable("Show");
                });

            modelBuilder.Entity("TVMaze.Infrastructure.Data.Entities.CastShow", b =>
                {
                    b.HasOne("TVMaze.Infrastructure.Data.Entities.Cast", "Cast")
                        .WithMany("CastShows")
                        .HasForeignKey("CastId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TVMaze.Infrastructure.Data.Entities.Show", "Show")
                        .WithMany("ShowCasts")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
